apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: readonly-binding
  namespace: dev
subjects:
- kind: ServiceAccount
  name: readonly-sa
roleRef:
  kind: Role
  name: readonly-role
  apiGroup: rbac.authorization.k8s.io
